"""Shared utility helpers for the MedCover application."""
from __future__ import annotations


def external_url_for(endpoint: str, **values: object) -> str:
    """Build an absolute URL for *endpoint*, honouring the configured ``app_base_url``.

    When ``AppSettings.app_base_url`` is set (e.g. ``https://medcoverdev.spidermila.site``),
    that base is prepended to the path generated by Flask's ``url_for``.  This ensures that
    links in e-mails (password reset, invitations, activation notices) point to the
    publicly accessible address even when the app runs behind a reverse proxy.

    Falls back to Flask's built-in ``_external=True`` behaviour when no base URL is
    configured so that local / test environments still produce valid links.
    """
    from flask import url_for

    try:
        from app.models.settings import get_settings
        base: str | None = get_settings().app_base_url
    except Exception:
        base = None

    path = url_for(endpoint, **values)  # type: ignore[arg-type]
    if base:
        return base.rstrip("/") + path
    return url_for(endpoint, _external=True, **values)  # type: ignore[arg-type]


def diff_changes(before: dict, after: dict) -> dict:
    """Return {field: [old_val, new_val]} for fields whose values changed.

    Compares using string representation so None and '' differences are caught.
    Only includes fields that actually changed — fields with identical values
    before and after are omitted.

    Example:
        before = {"name": "Old", "desc": None}
        after  = {"name": "New", "desc": None}
        → {"name": ["Old", "New"]}
    """
    all_keys = set(list(before.keys()) + list(after.keys()))
    return {
        k: [before.get(k), after.get(k)]
        for k in sorted(all_keys)
        if str(before.get(k)) != str(after.get(k))
    }
